## **1. Import Libraries**

In [321]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from sklearn.model_selection import GridSearchCV

## **2. Data Reading**

In [ ]:
# reading mushroom train data
url = "https://drive.google.com/file/d/1u5GNc48zNBOhpMP3A2CCy8vmYyhPG0aK/view?usp=share_link"
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
train = pd.read_csv(path)


# reading mushroom test data
url = "https://drive.google.com/file/d/1H5cuNzecAF1aJY-2ECxOTHSYGT-ABLuD/view?usp=share_link"
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
test = pd.read_csv(path)

In [ ]:
# X and y creation for train data
X = train.drop('Id',axis=1).copy()
Y = X.pop("poisonous")

In [ ]:
#test = test.drop('Id',axis=1).copy()

## **2. Data Manipulation**

In [ ]:
#To check categorical values
for i in X:
    print(i, " : ", X[i].unique())

cap.shape  :  ['k' 'f' 'b' 'x' 's' 'c']
cap.color  :  ['e' 'w' 'g' 'n' 'y' 'p' 'u' 'b' 'c' 'r']
bruises  :  [False  True]
stalk.color.above.ring  :  ['w' 'p' 'b' 'n' 'g' 'e' 'y' 'o' 'c']
stalk.color.below.ring  :  ['w' 'g' 'b' 'p' 'n' 'y' 'e' 'o' 'c']
population  :  ['v' 'y' 's' 'n' 'a' 'c']


In [ ]:
# initialize
my_onehot = OneHotEncoder()

# fit
my_onehot.fit(X)
my_onehot.fit(test) #for test data
# transform
X_onehot = my_onehot.transform(X)
test_onehot = my_onehot.transform(test)#for test data
X_onehot

<6499x42 sparse matrix of type '<class 'numpy.float64'>'
	with 38994 stored elements in Compressed Sparse Row format>

In [ ]:
test_onehot

<1625x42 sparse matrix of type '<class 'numpy.float64'>'
	with 9750 stored elements in Compressed Sparse Row format>

In [ ]:
X_onehot.toarray()
X_new = pd.DataFrame.sparse.from_spmatrix(X_onehot)
X_new.head()

0    1    2    3    4    5    6    7    8    9   ...   32   33   34   35  \
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  0.0   
1  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  0.0   
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0   
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  0.0   
4  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    36   37   38   39   40   41  
0  0.0  0.0  0.0  0.0  1.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  1.0  
2  0.0  0.0  0.0  1.0  0.0  0.0  
3  0.0  0.0  1.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  1.0  0.0  

[5 rows x 42 columns]

In [ ]:
#for test data
test_onehot.toarray()
test_new = pd.DataFrame.sparse.from_spmatrix(test_onehot)
test_new.head()

0    1    2    3    4    5    6    7    8    9   ...   32   33   34   35  \
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0   
1  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0   
3  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0   

    36   37   38   39   40   41  
0  0.0  0.0  0.0  0.0  1.0  0.0  
1  0.0  0.0  0.0  0.0  1.0  0.0  
2  0.0  0.0  0.0  0.0  1.0  0.0  
3  0.0  0.0  0.0  1.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  1.0  0.0  

[5 rows x 42 columns]

In [ ]:
colnames = my_onehot.get_feature_names_out(X.columns)
X_new.columns = colnames
X_new.head()

cap.shape_b  cap.shape_c  cap.shape_f  cap.shape_k  cap.shape_s  \
0          0.0          0.0          0.0          1.0          0.0   
1          0.0          0.0          1.0          0.0          0.0   
2          1.0          0.0          0.0          0.0          0.0   
3          0.0          0.0          0.0          1.0          0.0   
4          0.0          0.0          1.0          0.0          0.0   

   cap.shape_x  cap.color_b  cap.color_c  cap.color_e  cap.color_g  ...  \
0          0.0          0.0          0.0          1.0          0.0  ...   
1          0.0          0.0          0.0          1.0          0.0  ...   
2          0.0          0.0          0.0          0.0          0.0  ...   
3          0.0          0.0          0.0          0.0          1.0  ...   
4          0.0          0.0          0.0          0.0          0.0  ...   

   stalk.color.below.ring_o  stalk.color.below.ring_p  \
0                       0.0                       0.0   
1                       0.0                       0.0   
2                       0.0                       0.0   
3                       0.0                       0.0   
4                       0.0                       0.0   

   stalk.color.below.ring_w  stalk.color.below.ring_y  population_a  \
0                       1.0                       0.0           0.0   
1                       1.0                       0.0           0.0   
2                       1.0                       0.0           0.0   
3                       1.0                       0.0           0.0   
4                       0.0                       0.0           0.0   

   population_c  population_n  population_s  population_v  population_y  
0           0.0           0.0           0.0           1.0           0.0  
1           0.0           0.0           0.0           0.0           1.0  
2           0.0           0.0           1.0           0.0           0.0  
3           0.0           1.0           0.0           0.0           0.0  
4           0.0           0.0           0.0           1.0           0.0  

[5 rows x 42 columns]

In [ ]:
#for test data
colnames = my_onehot.get_feature_names_out(test.columns)
test_new.columns = colnames
test_new.head()

cap.shape_b  cap.shape_c  cap.shape_f  cap.shape_k  cap.shape_s  \
0          0.0          0.0          1.0          0.0          0.0   
1          0.0          0.0          1.0          0.0          0.0   
2          0.0          0.0          0.0          0.0          0.0   
3          0.0          0.0          1.0          0.0          0.0   
4          0.0          0.0          0.0          0.0          0.0   

   cap.shape_x  cap.color_b  cap.color_c  cap.color_e  cap.color_g  ...  \
0          0.0          0.0          0.0          0.0          0.0  ...   
1          0.0          0.0          0.0          0.0          1.0  ...   
2          1.0          0.0          0.0          0.0          0.0  ...   
3          0.0          0.0          0.0          0.0          0.0  ...   
4          1.0          0.0          0.0          0.0          0.0  ...   

   stalk.color.below.ring_o  stalk.color.below.ring_p  \
0                       0.0                       0.0   
1                       0.0                       1.0   
2                       0.0                       1.0   
3                       0.0                       0.0   
4                       0.0                       1.0   

   stalk.color.below.ring_w  stalk.color.below.ring_y  population_a  \
0                       1.0                       0.0           0.0   
1                       0.0                       0.0           0.0   
2                       0.0                       0.0           0.0   
3                       1.0                       0.0           0.0   
4                       0.0                       0.0           0.0   

   population_c  population_n  population_s  population_v  population_y  
0           0.0           0.0           0.0           1.0           0.0  
1           0.0           0.0           0.0           1.0           0.0  
2           0.0           0.0           0.0           1.0           0.0  
3           0.0           0.0           1.0           0.0           0.0  
4           0.0           0.0           0.0           1.0           0.0  

[5 rows x 42 columns]

In [ ]:
#All the train variables are in string/bool format. Convert categorical variables to integer using label encoder
#from sklearn.preprocessing import LabelEncoder
#lbl = LabelEncoder()

#for col in X.columns:
 #   X[col]=lbl.fit_transform(X[col])  

In [ ]:
#Test
#for col in test.columns:
 #   test[col]=lbl.fit_transform(test[col])

## **3. Classification Methods**

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X_new, Y, test_size = 0.25, random_state = 6)

In [ ]:
#Decision Tree
tree = DecisionTreeClassifier()
tree.fit(X_new, Y) #or try with X_train and Y_train
tree_pred = tree.predict(test_new)
acc_tree = round(accuracy_score(Y_test, tree.predict(test_new))*100,2)
acc_tree

49.72

In [ ]:
#AUC Score
tree_predict_prob = tree.predict_proba(test_new)
fpr, tpr, thresholds = roc_curve(Y_test, tree_predict_prob[:,1])
tree_auc = auc(fpr, tpr)
print(tree_auc)

0.4999772770652875


In [ ]:
#Logistic Regression Classification
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_new, Y)
lr_pred = lr.predict(test_new)
acc_lr = round(accuracy_score(Y_test, lr.predict(test_new))*100,2)
acc_lr

In [ ]:
lr_predict_prob = lr.predict_proba(test_new)
fpr, tpr, thresholds = roc_curve(Y_test, lr_predict_prob[:,1])
lr_auc = auc(fpr, tpr)
print(lr_auc)

0.49685817556042333


In [338]:
rf = RandomForestClassifier(n_estimators=7,criterion='gini',max_depth=5)
rf.fit(X_new, Y)
rf_pred = rf.predict(test_new)
acc_rf = round(accuracy_score(Y_test, rf.predict(test_new))*100,2)
acc_rf

50.4

In [339]:
rf_predict_prob = rf.predict_proba(test_new)
fpr, tpr, thresholds = roc_curve(Y_test, rf_predict_prob[:,1])
rf_auc = auc(fpr, tpr)
print(rf_auc)

0.5024404431881186


In [333]:
knn = KNeighborsClassifier(n_neighbors=5,weights='distance')
knn.fit(X_new,Y)
knn_pred = knn.predict(test_new)
acc_knn = round(accuracy_score(Y_test, knn.predict(test_new))*100,2)
acc_knn

50.28

In [323]:
#Checking performance our model with classification report.
from sklearn.metrics import classification_report
print(classification_report(Y_test, knn_pred))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50       807
           1       0.51      0.50      0.51       818

    accuracy                           0.50      1625
   macro avg       0.50      0.50      0.50      1625
weighted avg       0.50      0.50      0.50      1625



In [327]:
#Checking performance our model with ROC Score.
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test, knn_pred)

0.5027547771183077

In [312]:
knn_predict_prob = knn.predict_proba(test_new)
fpr, tpr, thresholds = roc_curve(Y_test, knn_predict_prob[:,1])
knn_auc = auc(fpr, tpr)
print(knn_auc)

0.498967621332897


In [340]:
#Which is the best Model ?
results = pd.DataFrame({
    'Model': ['Linear Regression','Random Forest','Decision Tree','KNN'],
    'Score': [acc_lr, acc_rf, acc_tree,acc_knn]})
result_df = results.sort_values(by='Score', ascending=False)
result_df = result_df.set_index('Score')
result_df.head()

Model
Score                   
50.40      Random Forest
50.28                KNN
49.72      Decision Tree
49.11  Linear Regression

## **4. Tune & Score**

In [341]:
#import metrics
from sklearn.metrics import confusion_matrix, accuracy_score

rf_conf_matrix = confusion_matrix(Y_test, rf_pred)
rf_accuracy = accuracy_score(Y_test, rf_pred)

print(rf_conf_matrix)
print(rf_accuracy)

[[471 336]
 [470 348]]
0.504


In [ ]:
tree_conf_matrix = confusion_matrix(Y_test, tree_pred)
tree_accuracy = accuracy_score(Y_test, tree_pred)

print(tree_conf_matrix)
print(tree_accuracy)

[[419 388]
 [432 386]]
0.49538461538461537


In [ ]:
lr_conf_matrix = confusion_matrix(Y_test, lr_pred)
lr_accuracy = accuracy_score(Y_test, lr_pred)

print(lr_conf_matrix)
print(lr_accuracy)

[[392 415]
 [413 405]]
0.49046153846153845


In [313]:
knn_conf_matrix = confusion_matrix(Y_test, knn_pred)
knn_accuracy = accuracy_score(Y_test, knn_pred)

print(knn_conf_matrix)
print(knn_accuracy)

[[404 403]
 [405 413]]
0.5027692307692307


In [315]:
from google.colab import files
df = pd.DataFrame().assign(Id=test['Id'], poisonous=knn_pred)
df.to_csv('sample_results.csv', index = False)
files.download("sample_results.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
#List Hyperparameters that we want to tune.
leaf_size = list(range(1,50))
n_neighbors = list(range(1,30))
p=[1,2]
#Convert to dictionary
hyperparameters = dict(leaf_size=leaf_size, n_neighbors=n_neighbors, p=p)
#Create new KNN object
knn = KNeighborsClassifier()
#Use GridSearch
clf = GridSearchCV(knn, hyperparameters, cv=10)
#Fit the model
best_model = clf.fit(X_new,Y)
#Print The value of best Hyperparameters
print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
print('Best p:', best_model.best_estimator_.get_params()['p'])
print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])